[package]
name = "argo"
version = "0.1.0"
edition = "2021"

[dependencies]
schemafy = "0.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[build-dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
